parserOptions:
  ecmaVersion: 11
  sourceType: module

rules:
  no-console: 0
  semi: [error,always]
  quotes: [error,double]

env: {
    browser: true,
    node: true,
  }

extends: "eslint:recommended"
